### ISSUE TITLE
Some questions of the research

### ISSUE THREAD

**Issue by LiShaoqian0609** [HKUST-Aerial-Robotics/GVINS#17]
Hello, 

Thank you for your great research! I would like to ask that are you considering of conducting a ultra-tightly coupled GNSS-Visual-Inertial system? From my point of view, the ultra-tightly couple GNSS-Inertial system is quite mature. What do you think are the difficulties of the conducting a ultra-tight couple in GNSS-Visual system?

Best, 

Shaoqian

**Comment by shaozu** [comment]
Hi, @LiShaoqian0609. Thanks for your interest. In the near future we have no plan on the ultra-tightly coupled GNSS fusion system. However, it is a good direction as the information from visual and inertial sensors will undoubtedly improve the GNSS signal tracking and measurement quality. At this stage I'm afraid that I cannot foresee the difficulties in such systems since I never tried the ultra-tight method.
